### ISSUE TITLE
Update to support 6.6.x

### ISSUE THREAD

**Issue by oztoteotl** [MrDrMcCoy/vrops-cluster-repair#1]
MrDrMcCoy

Are there any plans to upgrade this script to support later Versions of vROPS?

Cheers
Fan

**Comment by MrDrMcCoy** [comment]
Hi @oztoteotl,

I left VMware a little over a year ago, and my new work does not use VMware at all. As a result, I have sadly not kept up to date with the changes under the hood in the latest versions. If I remember correctly, the latest version at that time was 6.2. I heard rumors from development that back-end services within the product might be added or replaced as of 6.4+, but without a list of what changed and what the service dependency model is, I would likely do more harm than good in trying to keep this script up to date.

Also, looking back at the code in here, there are a lot of things I would do differently if I were to start over again. I think I would use Ansible or even vanilla Python to improve maintainability and ease of understanding. I'd be willing to undertake that effort, if I had a more technical list of changes to the later versions of vROPS.

Honestly, I'm a little sad that this script is still needed. If you'd be willing to share some of your experiences, I might be able to pass them along to a few of my contacts that are still at VMware and try to get you some better support at the very least. 

 - Jeremy
