### ISSUE TITLE
Can this project be removed?

### ISSUE THREAD

**Issue by miskowitch** [MrDrMcCoy/vrops-cluster-repair#2]
It is possible that it causes data corruption in later versions of vROps (6.6.1 and possibly earlier).  It shouldn't be needed in current/supported versions of vROps.

Can this be removed as no longer needed?

Thanks,
Rob

**Comment by MrDrMcCoy** [comment]
You got it, Rob. I'll replace it with an empty repo and message about safety issues in case anyone comes looking for it.

**Comment by miskowitch** [comment]
Thanks Jeremy.  Hope you are enjoying your new position!
Rob
